steps:
  # Step 1: Build the container image using Docker.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west6-docker.pkg.dev/agf-lens/lens-repo/lens-dashboard:latest',
      '.'
    ]
  
  # Step 2: Push the container image to Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west6-docker.pkg.dev/agf-lens/lens-repo/lens-dashboard:latest'
    ]
  
  # Step 3: Deploy the container image to Cloud Run with VPC connector settings.
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'lens-service',
      '--image', 'europe-west6-docker.pkg.dev/agf-lens/lens-repo/lens-dashboard:latest',
      '--platform', 'managed',
      '--region', 'europe-west6',
      '--allow-unauthenticated',
      '--vpc-connector', '$_VPC_CONNECTOR',
      '--vpc-egress', 'all-traffic'
    ]
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _LOCATION: europe-west6
  _REPO_NAME: lens-repo
  _YOUR_REGION: europe-west6
  _VPC_CONNECTOR: lens-connector
